on: repository_dispatch
name: Fetch DB from deposit github
jobs:
  fetch:
    name: Run local action
    runs-on: ubuntu-latest
    steps:
    - uses: ./fetch-proceedings-data 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
