name: pages
on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup
      uses: peaceiris/actions-hugo@v2.2.2
      with:
        hugo-version: 'latest'

    - name: Build
      run: |
          hugo --minify
          touch ./public/.nojekyll
          echo proceedings.juliacon.org > ./public/CNAME

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
